(function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):$jscomp.arrayIterator(b)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,e){b!=Array.prototype&&b!=Object.prototype&&(b[c]=e.value)};
$jscomp.polyfill=function(b,c,e,a){if(c){e=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var d=b[a];d in e||(e[d]={});e=e[d]}b=b[b.length-1];a=e[b];c=c(a);c!=a&&null!=c&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function c(){this.batch_=null}function e(a){return a instanceof d?a:new d(function(b,f){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;c.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};c.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var a=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){a(b,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(n){f||(f=!0,a.call(b,n))}}var b=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(f){this.reject_(f);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var k=new c;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(n){f.reject(n)}};d.prototype.then=function(a,b){function f(a,f){return"function"==typeof a?function(f){try{n(a(f))}catch(w){c(w)}}:
f}var n,c,e=new d(function(a,f){n=a;c=f});this.callWhenSettled_(f(a,n),f(b,c));return e};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function f(){switch(n.state_){case 1:a(n.result_);break;case 2:b(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?k.asyncExecute(f):this.onSettledCallbacks_.push(f)};d.resolve=e;d.reject=function(a){return new d(function(b,f){f(a)})};d.race=function(a){return new d(function(b,
f){for(var n=$jscomp.makeIterator(a),d=n.next();!d.done;d=n.next())e(d.value).callWhenSettled_(b,f)})};d.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?e([]):new d(function(a,d){function n(f){return function(b){c[f]=b;z--;0==z&&a(c)}}var c=[],z=0;do c.push(void 0),z++,e(f.value).callWhenSettled_(n(c.length-1),d),f=b.next();while(!f.done)})};return d},"es6","es3");
$jscomp.checkStringArgs=function(b,c,e){if(null==b)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,e){var a=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===e&&(e=a.length);e=Math.max(0,Math.min(e|0,a.length));for(var d=b.length;0<d&&0<e;)if(a[--e]!=b[--d])return!1;return 0>=d}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},c=Object.create(new $jscomp.global.Proxy(b,{get:function(e,a,d){return e==b&&"q"==a&&d==c}}));return!0===c.q}catch(e){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.owns=function(b,c){return Object.prototype.hasOwnProperty.call(b,c)};
$jscomp.polyfill("WeakMap",function(b){function c(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),d=Object.seal({}),c=new b([[a,2],[d,3]]);if(2!=c.get(a)||3!=c.get(d))return!1;c.delete(a);c.set(d,4);return!c.has(a)&&4==c.get(d)}catch(v){return!1}}function e(){}function a(a){if(!$jscomp.owns(a,k)){var f=new e;$jscomp.defineProperty(a,k,{value:f})}}function d(f){var b=Object[f];b&&(Object[f]=function(f){if(f instanceof e)return f;a(f);return b(f)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&
$jscomp.ES6_CONFORMANCE)return b}else if(c())return b;var k="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");var m=0,t=function(a){this.id_=(m+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var f;!(f=a.next()).done;)f=f.value,this.set(f[0],f[1])}};t.prototype.set=function(f,b){a(f);if(!$jscomp.owns(f,k))throw Error("WeakMap key fail: "+f);f[k][this.id_]=b;return this};t.prototype.get=function(a){return $jscomp.owns(a,k)?a[k][this.id_]:void 0};t.prototype.has=
function(a){return $jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)};t.prototype.delete=function(a){return $jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)?delete a[k][this.id_]:!1};return t},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function c(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),d=new b($jscomp.makeIterator([[a,"s"]]));if("s"!=d.get(a)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),e=c.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(c())return b;$jscomp.initSymbolIterator();var e=new WeakMap,a=function(a){this.data_={};this.head_=m();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};a.prototype.set=function(a,b){a=0===a?0:a;var f=d(this,a);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=b:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,this.size++);return this};a.prototype.delete=function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=m();this.size=0};a.prototype.has=function(a){return!!d(this,a).entry};
a.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};a.prototype.entries=function(){return k(this,function(a){return[a.key,a.value]})};a.prototype.keys=function(){return k(this,function(a){return a.key})};a.prototype.values=function(){return k(this,function(a){return a.value})};a.prototype.forEach=function(a,b){for(var f=this.entries(),d;!(d=f.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var d=function(a,b){var d=b&&typeof b;"object"==
d||"function"==d?e.has(b)?d=e.get(b):(d=""+ ++t,e.set(b,d)):d="p_"+b;var f=a.data_[d];if(f&&$jscomp.owns(a.data_,d))for(a=0;a<f.length;a++){var c=f[a];if(b!==b&&c.key!==c.key||b===c.key)return{id:d,list:f,index:a,entry:c}}return{id:d,list:f,index:-1,entry:void 0}},k=function(a,b){var d=a.head_;return $jscomp.iteratorPrototype(function(){if(d){for(;d.head!=a.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:b(d)};d=null}return{done:!0,value:void 0}})},m=function(){var a={};return a.previous=
a.next=a.head=a},t=0;return a},"es6","es3");
(function(b){function c(a){if(e[a])return e[a].exports;var d=e[a]={i:a,l:!1,exports:{}};b[a].call(d.exports,d,d.exports,c);d.l=!0;return d.exports}var e={};c.m=b;c.c=e;c.d=function(a,b,e){c.o(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:e})};c.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};c.t=function(a,b){b&1&&(a=c(a));if(b&8||b&4&&"object"===typeof a&&a&&a.__esModule)return a;
var d=Object.create(null);c.r(d);Object.defineProperty(d,"default",{enumerable:!0,value:a});if(b&2&&"string"!=typeof a)for(var e in a)c.d(d,e,function(b){return a[b]}.bind(null,e));return d};c.n=function(a){var b=a&&a.__esModule?function(){return a["default"]}:function(){return a};c.d(b,"a",b);return b};c.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};c.p="/core/office/";return c(c.s=12)})([function(b,c,e){e.d(c,"b",function(){return k});e.d(c,"c",function(){return d});e.d(c,"a",
function(){return m});var a=e(2),d=function(b,d){Object(a.a)("disableLogs")||(d?console.warn(b+": "+d):console.warn(b))},k=function(b,d){Object(a.a)("disableLogs")||(d?console.log(b+": "+d):console.log(b))},m=function(a,b){}},function(b,c,e){e.d(c,"a",function(){return w});e.d(c,"b",function(){return p});e.d(c,"c",function(){return h});var a=e(0),d=e(10),k="undefined"===typeof window?self:window,m=k.importScripts,t=function(a){if("string"===typeof a){for(var b=new Uint8Array(a.length),d=a.length,
g=0;g<d;g++)b[g]=a.charCodeAt(g);return b}return a},f=function(a){if("string"!==typeof a){for(var b="",d=0,g=a.length,c;d<g;)c=a.subarray(d,d+1024),d+=1024,b+=String.fromCharCode.apply(null,c);return b}return a},n=!1,z=function(a,b){n||(m(k.basePath+"decode.min.js"),n=!0);a=self.BrotliDecode(t(a));return b?a:f(a)};(function(){function a(){this.remainingDataArrays=[]}a.prototype.processRaw=function(a){return a};a.prototype.processBrotli=function(a){this.remainingDataArrays.push(a);return null};a.prototype.GetNextChunk=
function(a){this.decodeFunction||(this.decodeFunction=0===a[0]&&97===a[1]&&115===a[2]&&109===a[3]?this.processRaw:this.processBrotli);return this.decodeFunction(a)};a.prototype.End=function(){if(this.remainingDataArrays.length){for(var a=this.arrays,b=0,d=0;d<a.length;++d)b+=a[d].length;b=new Uint8Array(b);var g=0;for(d=0;d<a.length;++d){var c=a[d];b.set(c,g);g+=c.length}return z(b,!0)}return null};return a})();var v=!1,q=function(a,b){v||(m(k.basePath+"rawinflate.js",k.basePath+"pako_inflate.min.js"),
v=!0);var g=10;if("string"===typeof a){if(a.charCodeAt(3)&8){for(;0!==a.charCodeAt(g);++g);++g}}else if(a[3]&8){for(;0!==a[g];++g);++g}if(b)return a=t(a),a=a.subarray(g,a.length-8),k.pako.inflate(a,{windowBits:-15});a=f(a);a=a.substring(g,a.length-8);return d.a.inflate(a)},x=function(a,b){return b?a:f(a)},l=function(b){var d=!b.shouldOutputArray,g=new XMLHttpRequest;g.open("GET",b.url,b.isAsync);var c=d&&g.overrideMimeType;g.responseType=c?"text":"arraybuffer";c&&g.overrideMimeType("text/plain; charset=x-user-defined");
g.send();var e=function(){var e=Date.now();var h=c?g.responseText:new Uint8Array(g.response);Object(a.a)("worker","Result length is "+h.length);h.length<b.compressedMaximum?(h=b.decompressFunction(h,b.shouldOutputArray),Object(a.a)("worker","Decompressed length is "+h.length),Object(a.c)("There may be some degradation of performance. Your server has not been configured to serve .gz. and .br. files with the expected Content-Encoding. See http://www.pdftron.com/kb_content_encoding for instructions on how to resolve this.")):
d&&(h=f(h));Object(a.a)("worker",b.url+" Decompression took "+(Date.now()-e));return h};if(b.isAsync)var h=new Promise(function(a,d){g.onload=function(){200===this.status||0===this.status?a(e()):d("Download Failed "+b.url)};g.onerror=function(){d("Network error occurred "+b.url)}});else{if(200===g.status||0===g.status)return e();throw Error("Failed to load "+b.url);}return h},w=function(a){var b=a.lastIndexOf("/");-1===b&&(b=0);var d=a.slice(b).replace(".",".br.");return a.slice(0,b)+d},g=function(a,
b){var d=a.lastIndexOf("/");-1===d&&(d=0);var g=a.slice(d).replace(".",".gz.");b.url=a.slice(0,d)+g;b.decompressFunction=q;return l(b)},u=function(a,b){b.url=w(a);b.decompressFunction=z;return l(b)},r=function(a,b){a.endsWith(".js.mem")?a=a.slice(0,-4):a.endsWith(".mem")&&(a=a.slice(0,-4)+".js.mem");b.url=a;b.decompressFunction=x;return l(b)},y=function(b,d,g,c){return b.catch(function(b){Object(a.c)(b);return c(d,g)})},C=function(b,d,g){var c;if(g.isAsync){var f=d[0](b,g);for(c=1;c<d.length;++c)f=
y(f,b,g,d[c]);return f}for(c=0;c<d.length;++c)try{return d[c](b,g)}catch(H){Object(a.c)(H.message)}throw Error("");},h=function(a,b,d,c){return C(a,[g,u,r],{compressedMaximum:b,isAsync:d,shouldOutputArray:c})},p=function(a,b,d,c){return C(a,[u,g,r],{compressedMaximum:b,isAsync:d,shouldOutputArray:c})}},function(b,c,e){e.d(c,"a",function(){return k});e.d(c,"b",function(){return m});var a={},d={flattenedResources:!1,CANVAS_CACHE_SIZE:void 0,maxPagesBefore:void 0,maxPagesAhead:void 0,disableLogs:!1,
_trnDebugMode:!1,_logFiltersEnabled:null},k=function(a){return d[a]},m=function(b,c){var f;d[b]=c;null===(f=a[b])||void 0===f?void 0:f.forEach(function(a){a(c)})}},function(b,c,e){e.d(c,"c",function(){return m});e.d(c,"b",function(){return t});e.d(c,"a",function(){return f});var a="undefined"===typeof window?self:window;b=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?parseInt(a[2],10):a}();(function(){var b=a.navigator.userAgent.match(/Chrome\/(.*?) /);
return b?parseInt(b[1],10):b})();(function(){var b=a.navigator.userAgent.match(/OPR/),d=a.navigator.userAgent.match(/Maxthon/),c=a.navigator.userAgent.match(/Edge/);return a.navigator.userAgent.match(/Chrome\/(.*?) /)&&!b&&!d&&!c})();navigator.userAgent.match(/Edge/i);c=/iPad|iPhone|iPod/.test(a.navigator.platform)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints;var d=/^((?!chrome|android).)*safari/i.test(a.navigator.userAgent)||/^((?!chrome|android).)*$/.test(a.navigator.userAgent)&&
c;a.navigator.userAgent.match(/Firefox/);b||/Android|webOS|Touch|IEMobile|Silk/i.test(navigator.userAgent);navigator.userAgent.match(/(iPad|iPhone|iPod)/i);a.navigator.userAgent.indexOf("Android");var k=/Mac OS X 10_13_6.*\(KHTML, like Gecko\)$/.test(a.navigator.userAgent),m=function(){return d||k},t=!(!self.WebAssembly||!self.WebAssembly.validate),f=-1<a.navigator.userAgent.indexOf("Edge/16")||-1<a.navigator.userAgent.indexOf("MSAppHost")},function(b,c){c=function(){return this}();try{c=c||(new Function("return this"))()}catch(e){"object"===
typeof window&&(c=window)}b.exports=c},function(b,c,e){c.a=function(){ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);if(0>=b-a)return new ArrayBuffer(0);var d=new ArrayBuffer(b-a),c=new Uint8Array(d);a=new Uint8Array(this,a,b-a);c.set(a);return d})}},function(b,
c,e){e.d(c,"a",function(){return a});e(7);var a=function(a,b){return function(){}}},function(b,c,e){c.a=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}},function(b,c,e){e.d(c,"a",function(){return f});var a=e(9),d=e(1),k=e(11),m=e(3),t=function(){function a(a){var b=this;this.promise=a.then(function(a){b.response=a;b.status=200})}a.prototype.addEventListener=function(a,b){this.promise.then(b)};return a}(),f=function(b,c,
f){if(!m.b||m.a||Object(m.c)()||f){f=Object(d.b)((self.Module.asmjsPrefix?self.Module.asmjsPrefix:"")+b+".js.mem",c[".js.mem"],!1);var e=Object(d.c)((self.Module.memoryInitializerPrefixURL?self.Module.memoryInitializerPrefixURL:"")+b+".mem",c[".mem"],!0,!0);self.Module.memoryInitializerRequest=new t(e)}else self.Module.instantiateWasm=function(d,f){return Object(k.a)(Object(a.a)(),b+"Wasm.wasm",d,c["Wasm.wasm"]).then(function(a){f(a)})},f=Object(d.b)(b+"Wasm.js.mem",c["Wasm.js.mem"],!1,!1);f=new Blob([f],
{type:"application/javascript"});importScripts(URL.createObjectURL(f))}},function(b,c,e){function a(){return d}e.d(c,"a",function(){return a});var d=40},function(b,c,e){var a=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],d=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],m=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,
12289,16385,24577],t=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],f=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],n=function(){this.list=this.next=null},z=function(){this.n=this.b=this.e=0;this.t=null},v=function(a,b,d,g,c,f){this.BMAX=16;this.N_MAX=288;this.status=0;this.root=null;this.m=0;var e=Array(this.BMAX+1),u,h,p,k=Array(this.BMAX+1),t,r=new z,x=Array(this.BMAX);var l=Array(this.N_MAX);var w=Array(this.BMAX+1),F,D;var m=this.root=null;for(h=0;h<e.length;h++)e[h]=
0;for(h=0;h<k.length;h++)k[h]=0;for(h=0;h<x.length;h++)x[h]=null;for(h=0;h<l.length;h++)l[h]=0;for(h=0;h<w.length;h++)w[h]=0;var v=256<b?a[256]:this.BMAX;var A=a;var q=0;h=b;do e[A[q]]++,q++;while(0<--h);if(e[0]==b)this.root=null,this.status=this.m=0;else{for(p=1;p<=this.BMAX&&0==e[p];p++);var E=p;f<p&&(f=p);for(h=this.BMAX;0!=h&&0==e[h];h--);var J=h;f>h&&(f=h);for(F=1<<p;p<h;p++,F<<=1)if(0>(F-=e[p])){this.status=2;this.m=f;return}if(0>(F-=e[h]))this.status=2,this.m=f;else{e[h]+=F;w[1]=p=0;A=e;q=
1;for(t=2;0<--h;)w[t++]=p+=A[q++];A=a;h=q=0;do 0!=(p=A[q++])&&(l[w[p]++]=h);while(++h<b);b=w[J];w[0]=h=0;A=l;q=0;l=-1;var B=k[0]=0;t=null;for(D=0;E<=J;E++)for(a=e[E];0<a--;){for(;E>B+k[1+l];){B+=k[1+l];l++;D=(D=J-B)>f?f:D;if((u=1<<(p=E-B))>a+1)for(u-=a+1,t=E;++p<D&&!((u<<=1)<=e[++t]);)u-=e[t];B+p>v&&B<v&&(p=v-B);D=1<<p;k[1+l]=p;t=Array(D);for(u=0;u<D;u++)t[u]=new z;m=null==m?this.root=new n:m.next=new n;m.next=null;m.list=t;x[l]=t;0<l&&(w[l]=h,r.b=k[l],r.e=16+p,r.t=t,p=(h&(1<<B)-1)>>B-k[l],x[l-1][p].e=
r.e,x[l-1][p].b=r.b,x[l-1][p].n=r.n,x[l-1][p].t=r.t)}r.b=E-B;q>=b?r.e=99:A[q]<d?(r.e=256>A[q]?16:15,r.n=A[q++]):(r.e=c[A[q]-d],r.n=g[A[q++]-d]);u=1<<E-B;for(p=h>>B;p<D;p+=u)t[p].e=r.e,t[p].b=r.b,t[p].n=r.n,t[p].t=r.t;for(p=1<<E-1;0!=(h&p);p>>=1)h^=p;for(h^=p;(h&(1<<B)-1)!=w[l];)B-=k[l],l--}this.m=k[1];this.status=0!=F&&1!=J?1:0}}},q={Stream:function(a){this.zip_inflate_start();this.zip_inflate_data=a;this.zip_inflate_pos=0}};q.Stream.prototype={getBytes:function(a){for(var b,d=Array(1024),g=[],c=
0;c<a&&0<(b=this.zip_inflate_internal(d,0,d.length));)g[g.length]=String.fromCharCode.apply(null,d.slice(0,b)),c+=b;return c?(this.zip_inflate_data=this.zip_inflate_data.slice(this.zip_inflate_pos),this.zip_inflate_pos=0,g.join("")):""},zip_GET_BYTE:function(){return this.zip_inflate_data.length==this.zip_inflate_pos?-1:this.zip_inflate_data.charCodeAt(this.zip_inflate_pos++)&255},zip_NEEDBITS:function(a){for(;this.zip_bit_len<a;)this.zip_bit_buf|=this.zip_GET_BYTE()<<this.zip_bit_len,this.zip_bit_len+=
8},zip_GETBITS:function(b){return this.zip_bit_buf&a[b]},zip_DUMPBITS:function(a){this.zip_bit_buf>>=a;this.zip_bit_len-=a},zip_inflate_codes:function(a,b,d){var g,c;if(0==d)return 0;for(c=0;;){this.zip_NEEDBITS(this.zip_bl);var f=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];for(g=f.e;16<g;){if(99==g)return-1;this.zip_DUMPBITS(f.b);g-=16;this.zip_NEEDBITS(g);f=f.t[this.zip_GETBITS(g)];g=f.e}this.zip_DUMPBITS(f.b);if(16==g)this.zip_wp&=32767,a[b+c++]=this.zip_slide[this.zip_wp++]=f.n;else{if(15==
g)break;this.zip_NEEDBITS(g);this.zip_copy_leng=f.n+this.zip_GETBITS(g);this.zip_DUMPBITS(g);this.zip_NEEDBITS(this.zip_bd);f=this.zip_td.list[this.zip_GETBITS(this.zip_bd)];for(g=f.e;16<g;){if(99==g)return-1;this.zip_DUMPBITS(f.b);g-=16;this.zip_NEEDBITS(g);f=f.t[this.zip_GETBITS(g)];g=f.e}this.zip_DUMPBITS(f.b);this.zip_NEEDBITS(g);this.zip_copy_dist=this.zip_wp-f.n-this.zip_GETBITS(g);for(this.zip_DUMPBITS(g);0<this.zip_copy_leng&&c<d;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=
32767,a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++]}if(c==d)return d}this.zip_method=-1;return c},zip_inflate_stored:function(a,b,d){var g=this.zip_bit_len&7;this.zip_DUMPBITS(g);this.zip_NEEDBITS(16);g=this.zip_GETBITS(16);this.zip_DUMPBITS(16);this.zip_NEEDBITS(16);if(g!=(~this.zip_bit_buf&65535))return-1;this.zip_DUMPBITS(16);this.zip_copy_leng=g;for(g=0;0<this.zip_copy_leng&&g<d;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+g++]=this.zip_slide[this.zip_wp++]=
this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1);return g},zip_inflate_fixed:function(a,b,c){if(null==this.zip_fixed_tl){var g,f=Array(288);for(g=0;144>g;g++)f[g]=8;for(;256>g;g++)f[g]=9;for(;280>g;g++)f[g]=7;for(;288>g;g++)f[g]=8;this.zip_fixed_bl=7;g=new v(f,288,257,d,k,this.zip_fixed_bl);if(0!=g.status)return alert("HufBuild error: ".concat(g.status)),-1;this.zip_fixed_tl=g.root;this.zip_fixed_bl=g.m;for(g=0;30>g;g++)f[g]=5;this.zip_fixed_bd=5;g=new v(f,30,0,
m,t,this.zip_fixed_bd);if(1<g.status)return this.zip_fixed_tl=null,alert("HufBuild error: ".concat(g.status)),-1;this.zip_fixed_td=g.root;this.zip_fixed_bd=g.m}this.zip_tl=this.zip_fixed_tl;this.zip_td=this.zip_fixed_td;this.zip_bl=this.zip_fixed_bl;this.zip_bd=this.zip_fixed_bd;return this.zip_inflate_codes(a,b,c)},zip_inflate_dynamic:function(a,b,c){var g,e,r,l=Array(316);for(g=0;g<l.length;g++)l[g]=0;this.zip_NEEDBITS(5);var n=257+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(5);var h=
1+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(4);g=4+this.zip_GETBITS(4);this.zip_DUMPBITS(4);if(286<n||30<h)return-1;for(e=0;e<g;e++)this.zip_NEEDBITS(3),l[f[e]]=this.zip_GETBITS(3),this.zip_DUMPBITS(3);for(;19>e;e++)l[f[e]]=0;this.zip_bl=7;e=new v(l,19,19,null,null,this.zip_bl);if(0!=e.status)return-1;this.zip_tl=e.root;this.zip_bl=e.m;var p=n+h;for(g=r=0;g<p;){this.zip_NEEDBITS(this.zip_bl);var q=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];e=q.b;this.zip_DUMPBITS(e);e=q.n;if(16>
e)l[g++]=r=e;else if(16==e){this.zip_NEEDBITS(2);e=3+this.zip_GETBITS(2);this.zip_DUMPBITS(2);if(g+e>p)return-1;for(;0<e--;)l[g++]=r}else{17==e?(this.zip_NEEDBITS(3),e=3+this.zip_GETBITS(3),this.zip_DUMPBITS(3)):(this.zip_NEEDBITS(7),e=11+this.zip_GETBITS(7),this.zip_DUMPBITS(7));if(g+e>p)return-1;for(;0<e--;)l[g++]=0;r=0}}this.zip_bl=9;e=new v(l,n,257,d,k,this.zip_bl);0==this.zip_bl&&(e.status=1);if(0!=e.status)return-1;this.zip_tl=e.root;this.zip_bl=e.m;for(g=0;g<h;g++)l[g]=l[g+n];this.zip_bd=6;
e=new v(l,h,0,m,t,this.zip_bd);this.zip_td=e.root;this.zip_bd=e.m;return 0==this.zip_bd&&257<n||0!=e.status?-1:this.zip_inflate_codes(a,b,c)},zip_inflate_start:function(){null==this.zip_slide&&(this.zip_slide=Array(65536));this.zip_bit_len=this.zip_bit_buf=this.zip_wp=0;this.zip_method=-1;this.zip_eof=!1;this.zip_copy_leng=this.zip_copy_dist=0;this.zip_fixed_tl=this.zip_tl=null},zip_inflate_internal:function(a,b,d){var c;for(c=0;c<d&&(!this.zip_eof||-1!=this.zip_method);){if(0<this.zip_copy_leng){if(0!=
this.zip_method)for(;0<this.zip_copy_leng&&c<d;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++];else{for(;0<this.zip_copy_leng&&c<d;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1)}if(c==d)break}if(-1==this.zip_method){if(this.zip_eof)break;this.zip_NEEDBITS(1);0!=this.zip_GETBITS(1)&&
(this.zip_eof=!0);this.zip_DUMPBITS(1);this.zip_NEEDBITS(2);this.zip_method=this.zip_GETBITS(2);this.zip_DUMPBITS(2);this.zip_tl=null;this.zip_copy_leng=0}switch(this.zip_method){case 0:var e=this.zip_inflate_stored(a,b+c,d-c);break;case 1:e=null!=this.zip_tl?this.zip_inflate_codes(a,b+c,d-c):this.zip_inflate_fixed(a,b+c,d-c);break;case 2:e=null!=this.zip_tl?this.zip_inflate_codes(a,b+c,d-c):this.zip_inflate_dynamic(a,b+c,d-c);break;default:e=-1}if(-1==e)return this.zip_eof?0:-1;c+=e}return c}};q.inflate=
function(a){return(new q.Stream(a)).getBytes(4E9)};c.a=q},function(b,c,e){function a(a){return new Promise(function(b,d){var c=indexedDB.open(f,a);c.onerror=d.bind(null,"Error opening wasm cache database");c.onsuccess=function(){b(c.result)};c.onupgradeneeded=function(a){var b=c.result;b.objectStoreNames.contains(n)&&(Object(m.b)("Clearing out version "+a.oldVersion+" wasm cache"),b.deleteObjectStore(n));Object(m.b)("Creating version "+a.newVersion+" wasm cache");b.createObjectStore(n)}})}function d(a,
b){return new Promise(function(d,c){var e=a.transaction([n]).objectStore(n).get(b);e.onsuccess=function(){e.result?d(e.result):c("Module "+b+" was not found in wasm cache")};e.onerror=c.bind(null,"Error getting wasm module "+b)})}function k(b,c,e,f){function k(a,b){a=a.transaction([n],"readwrite").objectStore(n).put(b,c);a.onerror=function(a){Object(m.b)("Failed to store in wasm cache: "+a)};a.onsuccess=function(a){Object(m.b)("Successfully stored "+c+" in wasm cache")}}function q(a){u=u||Date.now();
return a?(Object(m.a)("load","Try instantiateStreaming"),fetch(Object(t.a)(c)).then(function(a){return WebAssembly.instantiateStreaming(a,e)}).catch(function(a){Object(m.a)("load","instantiateStreaming Failed "+c+" message "+a.message);return q(!1)})):Object(t.b)(c,f,!0,!0).then(function(a){g=Date.now();Object(m.a)("load","Request took "+(g-u)+" ms");return WebAssembly.instantiate(a,e)})}var g,u;return a(b).then(function(a){return d(a,c).then(function(a){Object(m.b)("Found "+c+" in wasm cache");return WebAssembly.instantiate(a,
e)},function(b){Object(m.a)(b);return q(!!WebAssembly.instantiateStreaming).then(function(b){try{Object(m.a)("load","WASM compilation took "+(Date.now()-(g||u))+" ms"),k(a,b.module)}catch(h){}return b.instance})})},function(a){Object(m.b)(a);return q().then(function(a){return a.instance})})}e.d(c,"a",function(){return k});var m=e(0),t=e(1),f="wasm-cache",n="wasm-cache"},function(b,c,e){b.exports=e(13)},function(b,c,e){e.r(c);e(14);e(19);b=e(5);e(20);Object(b.a)()},function(b,c,e){(function(a,b){function c(a){"@babel/helpers - typeof";
c="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return c(a)}(function(a){function d(){for(var a=0;a<G.length;a++)G[a][0](G[a][1]);G=[];H=!1}function f(a,b){G.push([a,b]);H||(H=!0,M(d,0))}function k(a,b){function c(a){q(b,a)}function d(a){l(b,a)}try{a(c,d)}catch(A){d(A)}}function m(a){var b=a.owner,c=b.state_;b=b.data_;var d=a[c];a=a.then;if("function"===
typeof d){c=I;try{b=d(b)}catch(A){l(a,A)}}v(a,b)||(c===I&&q(a,b),c===K&&l(a,b))}function v(a,b){var d;try{if(a===b)throw new TypeError("A promises callback cannot return that same promise.");if(b&&("function"===typeof b||"object"===c(b))){var e=b.then;if("function"===typeof e)return e.call(b,function(c){d||(d=!0,b!==c?q(a,c):x(a,c))},function(b){d||(d=!0,l(a,b))}),!0}}catch(A){return d||l(a,A),!0}return!1}function q(a,b){a!==b&&v(a,b)||x(a,b)}function x(a,b){a.state_===h&&(a.state_=p,a.data_=b,f(g,
a))}function l(a,b){a.state_===h&&(a.state_=p,a.data_=b,f(u,a))}function w(a){var b=a.then_;a.then_=void 0;for(a=0;a<b.length;a++)m(b[a])}function g(a){a.state_=I;w(a)}function u(a){a.state_=K;w(a)}function r(a){if("function"!==typeof a)throw new TypeError("Promise constructor takes a function argument");if(!1===this instanceof r)throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");this.then_=[];k(a,this)}a.createPromiseCapability=
function(){var a={},b=new r(function(b,c){a.resolve=b;a.reject=c});a.promise=b;return a};var y=a.Promise,C=y&&"resolve"in y&&"reject"in y&&"all"in y&&"race"in y&&function(){var a;new y(function(b){a=b});return"function"===typeof a}();"undefined"!==typeof exports&&exports?(exports.Promise=C?y:r,exports.Polyfill=r):"function"===typeof define&&e(18)?define(function(){return C?y:r}):C||(a.Promise=r);var h="pending",p="sealed",I="fulfilled",K="rejected",L=function(){},M="undefined"!==typeof b?b:setTimeout,
G=[],H;r.prototype={constructor:r,state_:h,then_:null,data_:void 0,then:function(a,b){a={owner:this,then:new this.constructor(L),fulfilled:a,rejected:b};this.state_===I||this.state_===K?f(m,a):this.then_.push(a);return a.then},"catch":function(a){return this.then(null,a)}};r.all=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.all().");return new this(function(b,c){function d(a){f++;return function(c){e[a]=c;--f||b(e)}}for(var e=
[],f=0,g=0,h;g<a.length;g++)(h=a[g])&&"function"===typeof h.then?h.then(d(g),c):e[g]=h;f||b(e)})};r.race=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.race().");return new this(function(b,c){for(var d=0,e;d<a.length;d++)(e=a[d])&&"function"===typeof e.then?e.then(b,c):b(e)})};r.resolve=function(a){return a&&"object"===c(a)&&a.constructor===this?a:new this(function(b){b(a)})};r.reject=function(a){return new this(function(b,
c){c(a)})}})("undefined"!==typeof window?window:"undefined"!==typeof a?a:"undefined"!==typeof self?self:void 0)}).call(this,e(4),e(15).setImmediate)},function(b,c,e){(function(a){function b(a,b){this._id=a;this._clearFn=b}var k="undefined"!==typeof a&&a||"undefined"!==typeof self&&self||window,m=Function.prototype.apply;c.setTimeout=function(){return new b(m.call(setTimeout,k,arguments),clearTimeout)};c.setInterval=function(){return new b(m.call(setInterval,k,arguments),clearInterval)};c.clearTimeout=
c.clearInterval=function(a){a&&a.close()};b.prototype.unref=b.prototype.ref=function(){};b.prototype.close=function(){this._clearFn.call(k,this._id)};c.enroll=function(a,b){clearTimeout(a._idleTimeoutId);a._idleTimeout=b};c.unenroll=function(a){clearTimeout(a._idleTimeoutId);a._idleTimeout=-1};c._unrefActive=c.active=function(a){clearTimeout(a._idleTimeoutId);var b=a._idleTimeout;0<=b&&(a._idleTimeoutId=setTimeout(function(){a._onTimeout&&a._onTimeout()},b))};e(16);c.setImmediate="undefined"!==typeof self&&
self.setImmediate||"undefined"!==typeof a&&a.setImmediate||this&&this.setImmediate;c.clearImmediate="undefined"!==typeof self&&self.clearImmediate||"undefined"!==typeof a&&a.clearImmediate||this&&this.clearImmediate}).call(this,e(4))},function(b,c,e){(function(a,b){(function(a,c){function d(a){delete g[a]}function e(a){if(u)setTimeout(e,0,a);else{var b=g[a];if(b){u=!0;try{var f=b.callback,h=b.args;switch(h.length){case 0:f();break;case 1:f(h[0]);break;case 2:f(h[0],h[1]);break;case 3:f(h[0],h[1],
h[2]);break;default:f.apply(c,h)}}finally{d(a),u=!1}}}}function k(){y=function(a){b.nextTick(function(){e(a)})}}function m(){if(a.postMessage&&!a.importScripts){var b=!0,c=a.onmessage;a.onmessage=function(){b=!1};a.postMessage("","*");a.onmessage=c;return b}}function v(){var b="setImmediate$"+Math.random()+"$",c=function(c){c.source===a&&"string"===typeof c.data&&0===c.data.indexOf(b)&&e(+c.data.slice(b.length))};a.addEventListener?a.addEventListener("message",c,!1):a.attachEvent("onmessage",c);y=
function(c){a.postMessage(b+c,"*")}}function q(){var a=new MessageChannel;a.port1.onmessage=function(a){e(a.data)};y=function(b){a.port2.postMessage(b)}}function x(){var a=r.documentElement;y=function(b){var c=r.createElement("script");c.onreadystatechange=function(){e(b);c.onreadystatechange=null;a.removeChild(c);c=null};a.appendChild(c)}}function l(){y=function(a){setTimeout(e,0,a)}}if(!a.setImmediate){var w=1,g={},u=!1,r=a.document,y,C=Object.getPrototypeOf&&Object.getPrototypeOf(a);C=C&&C.setTimeout?
C:a;"[object process]"==={}.toString.call(a.process)?k():m()?v():a.MessageChannel?q():r&&"onreadystatechange"in r.createElement("script")?x():l();C.setImmediate=function(a){"function"!==typeof a&&(a=new Function(""+a));for(var b=Array(arguments.length-1),c=0;c<b.length;c++)b[c]=arguments[c+1];g[w]={callback:a,args:b};y(w);return w++};C.clearImmediate=d}})("undefined"===typeof self?"undefined"===typeof a?this:a:self)}).call(this,e(4),e(17))},function(b,c){function e(){throw Error("setTimeout has not been defined");
}function a(){throw Error("clearTimeout has not been defined");}function d(a){if(z===setTimeout)return setTimeout(a,0);if((z===e||!z)&&setTimeout)return z=setTimeout,setTimeout(a,0);try{return z(a,0)}catch(u){try{return z.call(null,a,0)}catch(r){return z.call(this,a,0)}}}function k(b){if(v===clearTimeout)return clearTimeout(b);if((v===a||!v)&&clearTimeout)return v=clearTimeout,clearTimeout(b);try{return v(b)}catch(u){try{return v.call(null,b)}catch(r){return v.call(this,b)}}}function m(){x&&l&&(x=
!1,l.length?q=l.concat(q):w=-1,q.length&&t())}function t(){if(!x){var a=d(m);x=!0;for(var b=q.length;b;){l=q;for(q=[];++w<b;)l&&l[w].run();w=-1;b=q.length}l=null;x=!1;k(a)}}function f(a,b){this.fun=a;this.array=b}function n(){}b=b.exports={};try{var z="function"===typeof setTimeout?setTimeout:e}catch(g){z=e}try{var v="function"===typeof clearTimeout?clearTimeout:a}catch(g){v=a}var q=[],x=!1,l,w=-1;b.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-
1]=arguments[c];q.push(new f(a,b));1!==q.length||x||d(t)};f.prototype.run=function(){this.fun.apply(null,this.array)};b.title="browser";b.browser=!0;b.env={};b.argv=[];b.version="";b.versions={};b.on=n;b.addListener=n;b.once=n;b.off=n;b.removeListener=n;b.removeAllListeners=n;b.emit=n;b.prependListener=n;b.prependOnceListener=n;b.listeners=function(a){return[]};b.binding=function(a){throw Error("process.binding is not supported");};b.cwd=function(){return"/"};b.chdir=function(a){throw Error("process.chdir is not supported");
};b.umask=function(){return 0}},function(b,c){b.exports={}},function(b,c,e){(function(a){"undefined"===typeof a.crypto&&(a.crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()}})})("undefined"===typeof window?self:window)},function(b,c,e){function a(b){"@babel/helpers - typeof";a="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":
typeof a};return a(b)}var d=e(6),k=e(8),m=null;(function(b){function c(){v=function(){}}function e(b){var c=[];return{resource_array:c,msg:JSON.stringify(b.data,function(b,d){if("object"===a(d)&&(b=null,d instanceof Uint8Array?b=d:d instanceof ArrayBuffer&&(b=new Uint8Array(d)),b)){d=x(b.length);var e=l(d);e&&(new Uint8Array(Module.HEAPU8.buffer,e,b.length)).set(b);c.push(d);return{__trn_res_id:d}}return d})}}function t(a){a=e(a);q(a.msg)}var v,q,x,l;b.basePath="../";var w=b.officeWorkerPath||"";
b.workerBasePath&&(b.basePath=b.workerBasePath);var g=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}(b.location.search);b.basePath=g.externalPath?g.externalPath:b.basePath+"external/";importScripts("".concat(b.basePath,"Promise.js"));var u=[];onmessage=function(a){u||(u=[]);u.push(a)};b.ContinueFunc=function(a){v("ContinueFunc called");setTimeout(function(){onmessage({data:{action:"continue"}})},a)};if(g.pdfWorkerPath)var r=
g.pdfWorkerPath;if(g.officeAsmPath)var y=g.officeAsmPath;b.Module={memoryInitializerPrefixURL:r,asmjsPrefix:y,onRuntimeInitialized:function(){v||c();var a=Date.now()-m;Object(d.a)("load","time duration from start to ready: ".concat(JSON.stringify(a)));q=function(a){if(null!==a&&void 0!==a&&0!==a){var b=(a.length<<2)+1,c=Module._malloc(b);0<Module.stringToUTF8(a,c,b)&&Module._TRN_OnMessage(c)}};x=function(a){return Module._TRN_CreateBufferResource(a)};l=function(a){return Module._TRN_GetResourcePointer(a)};
v("OnReady called");onmessage=t;Module._TRN_InitWorker();for(a=0;a<u.length;++a)onmessage(u[a]);u=null},fetchSelf:function(){m=Date.now();Object(k.a)("".concat(w,"WebOfficeWorker"),{"Wasm.wasm":5E6,"Wasm.js.mem":1E5,".js.mem":5E6,".mem":3E6},!!navigator.userAgent.match(/Edge/i))},noExitRuntime:!0};b.Module.fetchSelf()})("undefined"===typeof window?self:window)}]);}).call(this || window)
